spring:
  datasource:
    url: jdbc:mysql://matt.cpacw9fl5njb.ap-northeast-2.rds.amazonaws.com:3306/matt
    username: admin
    password: admin0810
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    #    org.hibernate.sql: debug
    org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie
<<<<<<< HEAD
  port: 8999



=======
  port: 8999
>>>>>>> 2ede074a8aff9506dc9daa03fb65bec51b12935f
